// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Enum.proto
// Protobuf C++ Version: 5.29.5

#ifndef Enum_2eproto_2epb_2eh
#define Enum_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Enum_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {
enum ComponentID : int {
  COMPONENT_TPYE_ENGINE_START = 0,
  COMPONENT_TYPE_TRANSFORM = 1,
  COMPONENT_TYPE_TEXTURE = 2,
  COMPONENT_TYPE_COLLIDER = 3,
  COMPONENT_TYPE_RECT = 4,
  COMPONENT_TYPE_SHADER = 5,
  COMPONENT_TYPE_TERRAIN = 6,
  COMPONENT_TYPE_MODEL = 7,
  COMPONENT_TYPE_PROJECTILE = 8,
  COMPONENT_TYPE_COLLIDER_AABB = 21,
  COMPONENT_TYPE_COLLIDER_OBB = 22,
  COMPONENT_TYPE_COLLIDER_SPHERE = 23,
  COMPONENT_TYPE_COLLIDER_CAPSULE = 24,
  COMPONENT_TYPE_BEHAVIOR = 100,
  COMPONENT_TYPE_CONTROLLER = 101,
  COMPONENT_TYPE_TEXTURE_START = 200,
  COMPONENT_TYPE_TEXTURE_DEFAULT = 201,
  COMPONENT_TYPE_TEXTURE_TERRAIN = 202,
  COMPONENT_TYPE_TEXTURE_PLAYER = 203,
  COMPONENT_TYPE_TEXTURE_MONSTER = 204,
  COMPONENT_TYPE_TEXTURE_MAIN_TITLE = 205,
  COMPONENT_TYPE_TEXTURE_LOADING = 206,
  COMPONENT_TYPE_TEXTURE_SKILL_GAUGE = 207,
  COMPONENT_TYPE_TEXTURE_SKILL_ICON = 208,
  COMPONENT_TYPE_TEXTURE_PLAYER_STATUS = 209,
  COMPONENT_TYPE_TEXTURE_EQUIPMENT = 210,
  COMPONENT_TYPE_TEXTURE_SKILL_SUB = 211,
  COMPONENT_TYPE_TEXTURE_WEAPON_TYPE = 212,
  COMPONENT_TYPE_TEXTURE_ANNOUNCE_HIT = 213,
  COMPONENT_TYPE_TEXTURE_ANNOUNCE_DIGIT = 214,
  COMPONENT_TYPE_TEXTURE_TARGET = 215,
  COMPONENT_TYPE_MESH = 299,
  COMPONENT_TYPE_MODEL_START = 300,
  COMPONENT_TYPE_MODEL_PLAYER = 301,
  COMPONENT_TYPE_MODEL_MONSTER = 302,
  COMPONENT_TYPE_MODEL_SASKE = 303,
  COMPONENT_TYPE_SHADER_START = 400,
  COMPONENT_TYPE_SHADER_VTXTEX = 401,
  COMPONENT_TYPE_SHADER_VTXNORTEX = 402,
  COMPONENT_TYPE_SHADER_VTXMESH = 403,
  COMPONENT_TYPE_SHADER_VTXANIMMESH = 404,
  COMPONENT_TYPE_SHADER_UI = 405,
  COMPONENT_TYPE_SHADER_STATIC_MESH = 406,
  COMPONENT_TYPE_CLIENT_START = 1000,
  COMPONENT_TYPE_REPLICATOR = 1001,
  COMPONENT_TYPE_COMBAT_STAT = 1002,
  COMPONENT_TYPE_PLAYER_CONTROLLER = 1003,
  COMPONENT_TYPE_AI_CONTROLLER = 1004,
  COMPONENT_TYPE_MOVEMENT = 1005,
  COMPONENT_TYPE_INPUT = 1006,
  COMPONENT_TYPE_PLAYER_STATE = 1007,
  COMPONENT_TYPE_SKILL = 1008,
  COMPONENT_TYPE_ANIMATION_STATE = 1009,
  COMPONENT_TYPE_EQUIPMENT = 1010,
  COMPONENT_TYPE_TARGET = 1011,
  ComponentID_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ComponentID_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ComponentID_IsValid(int value);
extern const uint32_t ComponentID_internal_data_[];
constexpr ComponentID ComponentID_MIN = static_cast<ComponentID>(0);
constexpr ComponentID ComponentID_MAX = static_cast<ComponentID>(1011);
constexpr int ComponentID_ARRAYSIZE = 1011 + 1;
const ::google::protobuf::EnumDescriptor*
ComponentID_descriptor();
template <typename T>
const std::string& ComponentID_Name(T value) {
  static_assert(std::is_same<T, ComponentID>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ComponentID_Name().");
  return ::google::protobuf::internal::NameOfEnum(ComponentID_descriptor(), value);
}
inline bool ComponentID_Parse(absl::string_view name, ComponentID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ComponentID>(
      ComponentID_descriptor(), name, value);
}
enum OBJECT_TYPE : int {
  OBJECT_TYPE_NONE = 0,
  OBJECT_TYPE_PLAYER = 1,
  OBJECT_TYPE_REMOTE_PLAYER = 2,
  OBJECT_TYPE_PREVIEW_PLAYER = 3,
  OBJECT_TYPE_MONSTER = 4,
  OBJECT_TYPE_CAMERA_FREE = 5,
  OBJECT_TYPE_CAMERA_TARGET = 6,
  OBJECT_TYPE_CAMERA_CINEMATIC = 7,
  OBJECT_TYPE_PLAYER_START = 10,
  OBJECT_TYPE_TERRAIN = 11,
  OBJECT_TYPE_BACKGROUND = 12,
  OBJECT_TYPE_STATIC_MESH = 13,
  OBJECT_TYPE_PART_OBJECT = 14,
  OBJECT_TYPE_PART_WEAPON = 15,
  OBJECT_TYPE_SKILL_OBJECT = 16,
  OBJECT_TYPE_SKILL_PROJECTILE = 17,
  OBJECT_TYPE_SKILL_RASENGAN = 18,
  OBJECT_TYPE_SKILL_RASENSHURIKEN = 19,
  OBJECT_TYPE_UI_TEXT = 100,
  OBJECT_TYPE_UI_LOADING_SPINNER = 101,
  OBJECT_TYPE_UI_LOADING_PROGRESS_BAR = 102,
  OBJECT_TYPE_UI_MAIN_TITLE_TEXT = 103,
  OBJECT_TYPE_UI_PLAYER_HP = 104,
  OBJECT_TYPE_UI_SKILL_SLOT = 105,
  OBJECT_TYPE_UI_PLAYER_STATUS = 106,
  OBJECT_TYPE_UI_PLAYER_SKILL = 107,
  OBJECT_TYPE_UI_PLAYER_HUD = 108,
  OBJECT_TYPE_UI_TAB = 109,
  OBJECT_TYPE_UI_WEAPON_TYPE = 110,
  OBJECT_TYPE_UI_ANNOUNCE_COMBO = 111,
  OBJECT_TYPE_UI_TARGETING = 112,
  OBJECT_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  OBJECT_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool OBJECT_TYPE_IsValid(int value);
extern const uint32_t OBJECT_TYPE_internal_data_[];
constexpr OBJECT_TYPE OBJECT_TYPE_MIN = static_cast<OBJECT_TYPE>(0);
constexpr OBJECT_TYPE OBJECT_TYPE_MAX = static_cast<OBJECT_TYPE>(112);
constexpr int OBJECT_TYPE_ARRAYSIZE = 112 + 1;
const ::google::protobuf::EnumDescriptor*
OBJECT_TYPE_descriptor();
template <typename T>
const std::string& OBJECT_TYPE_Name(T value) {
  static_assert(std::is_same<T, OBJECT_TYPE>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to OBJECT_TYPE_Name().");
  return ::google::protobuf::internal::NameOfEnum(OBJECT_TYPE_descriptor(), value);
}
inline bool OBJECT_TYPE_Parse(absl::string_view name, OBJECT_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OBJECT_TYPE>(
      OBJECT_TYPE_descriptor(), name, value);
}
enum OBJECT_STATE_TYPE : int {
  OBJECT_STATE_TYPE_IDLE = 0,
  OBJECT_STATE_TYPE_RUN = 1,
  OBJECT_STATE_TYPE_JUMP = 2,
  OBJECT_STATE_TYPE_DOUBLE_JUMP = 3,
  OBJECT_STATE_TYPE_SUPER_JUMP_CHARGE = 4,
  OBJECT_STATE_TYPE_SUPER_JUMP = 5,
  OBJECT_STATE_TYPE_HEIGHT_LAND = 6,
  OBJECT_STATE_TYPE_DASH = 7,
  OBJECT_STATE_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  OBJECT_STATE_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool OBJECT_STATE_TYPE_IsValid(int value);
extern const uint32_t OBJECT_STATE_TYPE_internal_data_[];
constexpr OBJECT_STATE_TYPE OBJECT_STATE_TYPE_MIN = static_cast<OBJECT_STATE_TYPE>(0);
constexpr OBJECT_STATE_TYPE OBJECT_STATE_TYPE_MAX = static_cast<OBJECT_STATE_TYPE>(7);
constexpr int OBJECT_STATE_TYPE_ARRAYSIZE = 7 + 1;
const ::google::protobuf::EnumDescriptor*
OBJECT_STATE_TYPE_descriptor();
template <typename T>
const std::string& OBJECT_STATE_TYPE_Name(T value) {
  static_assert(std::is_same<T, OBJECT_STATE_TYPE>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to OBJECT_STATE_TYPE_Name().");
  return OBJECT_STATE_TYPE_Name(static_cast<OBJECT_STATE_TYPE>(value));
}
template <>
inline const std::string& OBJECT_STATE_TYPE_Name(OBJECT_STATE_TYPE value) {
  return ::google::protobuf::internal::NameOfDenseEnum<OBJECT_STATE_TYPE_descriptor,
                                                 0, 7>(
      static_cast<int>(value));
}
inline bool OBJECT_STATE_TYPE_Parse(absl::string_view name, OBJECT_STATE_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OBJECT_STATE_TYPE>(
      OBJECT_STATE_TYPE_descriptor(), name, value);
}
enum MOVE_INPUT_DIR_TYPE : int {
  MOVE_INPUT_DIR_TYPE_FORWARD = 0,
  MOVE_INPUT_DIR_TYPE_BACKWARD = 1,
  MOVE_INPUT_DIR_TYPE_LEFT = 2,
  MOVE_INPUT_DIR_TYPE_RIGHT = 3,
  MOVE_INPUT_DIR_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  MOVE_INPUT_DIR_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool MOVE_INPUT_DIR_TYPE_IsValid(int value);
extern const uint32_t MOVE_INPUT_DIR_TYPE_internal_data_[];
constexpr MOVE_INPUT_DIR_TYPE MOVE_INPUT_DIR_TYPE_MIN = static_cast<MOVE_INPUT_DIR_TYPE>(0);
constexpr MOVE_INPUT_DIR_TYPE MOVE_INPUT_DIR_TYPE_MAX = static_cast<MOVE_INPUT_DIR_TYPE>(3);
constexpr int MOVE_INPUT_DIR_TYPE_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
MOVE_INPUT_DIR_TYPE_descriptor();
template <typename T>
const std::string& MOVE_INPUT_DIR_TYPE_Name(T value) {
  static_assert(std::is_same<T, MOVE_INPUT_DIR_TYPE>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to MOVE_INPUT_DIR_TYPE_Name().");
  return MOVE_INPUT_DIR_TYPE_Name(static_cast<MOVE_INPUT_DIR_TYPE>(value));
}
template <>
inline const std::string& MOVE_INPUT_DIR_TYPE_Name(MOVE_INPUT_DIR_TYPE value) {
  return ::google::protobuf::internal::NameOfDenseEnum<MOVE_INPUT_DIR_TYPE_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool MOVE_INPUT_DIR_TYPE_Parse(absl::string_view name, MOVE_INPUT_DIR_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MOVE_INPUT_DIR_TYPE>(
      MOVE_INPUT_DIR_TYPE_descriptor(), name, value);
}
enum ANIM_PHASE_TYPE : int {
  ANIM_PHASE_START = 0,
  ANIM_PHASE_LOOP = 1,
  ANIM_PHASE_END = 2,
  ANIM_PHASE_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ANIM_PHASE_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ANIM_PHASE_TYPE_IsValid(int value);
extern const uint32_t ANIM_PHASE_TYPE_internal_data_[];
constexpr ANIM_PHASE_TYPE ANIM_PHASE_TYPE_MIN = static_cast<ANIM_PHASE_TYPE>(0);
constexpr ANIM_PHASE_TYPE ANIM_PHASE_TYPE_MAX = static_cast<ANIM_PHASE_TYPE>(2);
constexpr int ANIM_PHASE_TYPE_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
ANIM_PHASE_TYPE_descriptor();
template <typename T>
const std::string& ANIM_PHASE_TYPE_Name(T value) {
  static_assert(std::is_same<T, ANIM_PHASE_TYPE>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ANIM_PHASE_TYPE_Name().");
  return ANIM_PHASE_TYPE_Name(static_cast<ANIM_PHASE_TYPE>(value));
}
template <>
inline const std::string& ANIM_PHASE_TYPE_Name(ANIM_PHASE_TYPE value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ANIM_PHASE_TYPE_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool ANIM_PHASE_TYPE_Parse(absl::string_view name, ANIM_PHASE_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ANIM_PHASE_TYPE>(
      ANIM_PHASE_TYPE_descriptor(), name, value);
}
enum ATTACK_PROFILE_TYPE : int {
  ATTACK_PROFILE_TYPE_HAND_GROUND = 0,
  ATTACK_PROFILE_TYPE_HAND_AERIAL = 1,
  ATTACK_PROFILE_TYPE_BIGSWORD_GROUND = 2,
  ATTACK_PROFILE_TYPE_BIGSWORD_AERIAL = 3,
  ATTACK_PROFILE_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ATTACK_PROFILE_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ATTACK_PROFILE_TYPE_IsValid(int value);
extern const uint32_t ATTACK_PROFILE_TYPE_internal_data_[];
constexpr ATTACK_PROFILE_TYPE ATTACK_PROFILE_TYPE_MIN = static_cast<ATTACK_PROFILE_TYPE>(0);
constexpr ATTACK_PROFILE_TYPE ATTACK_PROFILE_TYPE_MAX = static_cast<ATTACK_PROFILE_TYPE>(3);
constexpr int ATTACK_PROFILE_TYPE_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
ATTACK_PROFILE_TYPE_descriptor();
template <typename T>
const std::string& ATTACK_PROFILE_TYPE_Name(T value) {
  static_assert(std::is_same<T, ATTACK_PROFILE_TYPE>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ATTACK_PROFILE_TYPE_Name().");
  return ATTACK_PROFILE_TYPE_Name(static_cast<ATTACK_PROFILE_TYPE>(value));
}
template <>
inline const std::string& ATTACK_PROFILE_TYPE_Name(ATTACK_PROFILE_TYPE value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ATTACK_PROFILE_TYPE_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool ATTACK_PROFILE_TYPE_Parse(absl::string_view name, ATTACK_PROFILE_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ATTACK_PROFILE_TYPE>(
      ATTACK_PROFILE_TYPE_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Protocol::ComponentID> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::ComponentID>() {
  return ::Protocol::ComponentID_descriptor();
}
template <>
struct is_proto_enum<::Protocol::OBJECT_TYPE> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::OBJECT_TYPE>() {
  return ::Protocol::OBJECT_TYPE_descriptor();
}
template <>
struct is_proto_enum<::Protocol::OBJECT_STATE_TYPE> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::OBJECT_STATE_TYPE>() {
  return ::Protocol::OBJECT_STATE_TYPE_descriptor();
}
template <>
struct is_proto_enum<::Protocol::MOVE_INPUT_DIR_TYPE> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::MOVE_INPUT_DIR_TYPE>() {
  return ::Protocol::MOVE_INPUT_DIR_TYPE_descriptor();
}
template <>
struct is_proto_enum<::Protocol::ANIM_PHASE_TYPE> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::ANIM_PHASE_TYPE>() {
  return ::Protocol::ANIM_PHASE_TYPE_descriptor();
}
template <>
struct is_proto_enum<::Protocol::ATTACK_PROFILE_TYPE> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::ATTACK_PROFILE_TYPE>() {
  return ::Protocol::ATTACK_PROFILE_TYPE_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Enum_2eproto_2epb_2eh
