// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Struct.proto
// Protobuf C++ Version: 5.29.5

#ifndef Struct_2eproto_2epb_2eh
#define Struct_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "Enum.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Struct_2eproto;
namespace Protocol {
class BuffData;
struct BuffDataDefaultTypeInternal;
extern BuffDataDefaultTypeInternal _BuffData_default_instance_;
class CombatStat;
struct CombatStatDefaultTypeInternal;
extern CombatStatDefaultTypeInternal _CombatStat_default_instance_;
class ObjectInfo;
struct ObjectInfoDefaultTypeInternal;
extern ObjectInfoDefaultTypeInternal _ObjectInfo_default_instance_;
class Vec3;
struct Vec3DefaultTypeInternal;
extern Vec3DefaultTypeInternal _Vec3_default_instance_;
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {

// ===================================================================


// -------------------------------------------------------------------

class Vec3 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.Vec3) */ {
 public:
  inline Vec3() : Vec3(nullptr) {}
  ~Vec3() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Vec3* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Vec3));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Vec3(
      ::google::protobuf::internal::ConstantInitialized);

  inline Vec3(const Vec3& from) : Vec3(nullptr, from) {}
  inline Vec3(Vec3&& from) noexcept
      : Vec3(nullptr, std::move(from)) {}
  inline Vec3& operator=(const Vec3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vec3& operator=(Vec3&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vec3& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vec3* internal_default_instance() {
    return reinterpret_cast<const Vec3*>(
        &_Vec3_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Vec3& a, Vec3& b) { a.Swap(&b); }
  inline void Swap(Vec3* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vec3* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vec3* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Vec3>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Vec3& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Vec3& from) { Vec3::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Vec3* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.Vec3"; }

 protected:
  explicit Vec3(::google::protobuf::Arena* arena);
  Vec3(::google::protobuf::Arena* arena, const Vec3& from);
  Vec3(::google::protobuf::Arena* arena, Vec3&& from) noexcept
      : Vec3(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 3;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.Vec3)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Vec3& from_msg);
    float x_;
    float y_;
    float z_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class CombatStat final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.CombatStat) */ {
 public:
  inline CombatStat() : CombatStat(nullptr) {}
  ~CombatStat() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CombatStat* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CombatStat));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CombatStat(
      ::google::protobuf::internal::ConstantInitialized);

  inline CombatStat(const CombatStat& from) : CombatStat(nullptr, from) {}
  inline CombatStat(CombatStat&& from) noexcept
      : CombatStat(nullptr, std::move(from)) {}
  inline CombatStat& operator=(const CombatStat& from) {
    CopyFrom(from);
    return *this;
  }
  inline CombatStat& operator=(CombatStat&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CombatStat& default_instance() {
    return *internal_default_instance();
  }
  static inline const CombatStat* internal_default_instance() {
    return reinterpret_cast<const CombatStat*>(
        &_CombatStat_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CombatStat& a, CombatStat& b) { a.Swap(&b); }
  inline void Swap(CombatStat* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CombatStat* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CombatStat* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CombatStat>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CombatStat& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CombatStat& from) { CombatStat::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CombatStat* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.CombatStat"; }

 protected:
  explicit CombatStat(::google::protobuf::Arena* arena);
  CombatStat(::google::protobuf::Arena* arena, const CombatStat& from);
  CombatStat(::google::protobuf::Arena* arena, CombatStat&& from) noexcept
      : CombatStat(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMaxHpFieldNumber = 1,
    kCurrentHpFieldNumber = 2,
    kMaxMpFieldNumber = 3,
    kCurrentMpFieldNumber = 4,
    kAttackFieldNumber = 5,
    kDefenseFieldNumber = 6,
    kSpeedFieldNumber = 7,
  };
  // float max_hp = 1;
  void clear_max_hp() ;
  float max_hp() const;
  void set_max_hp(float value);

  private:
  float _internal_max_hp() const;
  void _internal_set_max_hp(float value);

  public:
  // float current_hp = 2;
  void clear_current_hp() ;
  float current_hp() const;
  void set_current_hp(float value);

  private:
  float _internal_current_hp() const;
  void _internal_set_current_hp(float value);

  public:
  // float max_mp = 3;
  void clear_max_mp() ;
  float max_mp() const;
  void set_max_mp(float value);

  private:
  float _internal_max_mp() const;
  void _internal_set_max_mp(float value);

  public:
  // float current_mp = 4;
  void clear_current_mp() ;
  float current_mp() const;
  void set_current_mp(float value);

  private:
  float _internal_current_mp() const;
  void _internal_set_current_mp(float value);

  public:
  // float attack = 5;
  void clear_attack() ;
  float attack() const;
  void set_attack(float value);

  private:
  float _internal_attack() const;
  void _internal_set_attack(float value);

  public:
  // float defense = 6;
  void clear_defense() ;
  float defense() const;
  void set_defense(float value);

  private:
  float _internal_defense() const;
  void _internal_set_defense(float value);

  public:
  // float speed = 7;
  void clear_speed() ;
  float speed() const;
  void set_speed(float value);

  private:
  float _internal_speed() const;
  void _internal_set_speed(float value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.CombatStat)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CombatStat& from_msg);
    float max_hp_;
    float current_hp_;
    float max_mp_;
    float current_mp_;
    float attack_;
    float defense_;
    float speed_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class BuffData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.BuffData) */ {
 public:
  inline BuffData() : BuffData(nullptr) {}
  ~BuffData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BuffData* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BuffData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BuffData(
      ::google::protobuf::internal::ConstantInitialized);

  inline BuffData(const BuffData& from) : BuffData(nullptr, from) {}
  inline BuffData(BuffData&& from) noexcept
      : BuffData(nullptr, std::move(from)) {}
  inline BuffData& operator=(const BuffData& from) {
    CopyFrom(from);
    return *this;
  }
  inline BuffData& operator=(BuffData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BuffData& default_instance() {
    return *internal_default_instance();
  }
  static inline const BuffData* internal_default_instance() {
    return reinterpret_cast<const BuffData*>(
        &_BuffData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BuffData& a, BuffData& b) { a.Swap(&b); }
  inline void Swap(BuffData* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BuffData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BuffData* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BuffData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BuffData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BuffData& from) { BuffData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BuffData* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.BuffData"; }

 protected:
  explicit BuffData(::google::protobuf::Arena* arena);
  BuffData(::google::protobuf::Arena* arena, const BuffData& from);
  BuffData(::google::protobuf::Arena* arena, BuffData&& from) noexcept
      : BuffData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVictimsFieldNumber = 3,
    kBuffIdFieldNumber = 1,
    kRemainTimeFieldNumber = 2,
  };
  // repeated uint64 victims = 3;
  int victims_size() const;
  private:
  int _internal_victims_size() const;

  public:
  void clear_victims() ;
  ::uint64_t victims(int index) const;
  void set_victims(int index, ::uint64_t value);
  void add_victims(::uint64_t value);
  const ::google::protobuf::RepeatedField<::uint64_t>& victims() const;
  ::google::protobuf::RepeatedField<::uint64_t>* mutable_victims();

  private:
  const ::google::protobuf::RepeatedField<::uint64_t>& _internal_victims() const;
  ::google::protobuf::RepeatedField<::uint64_t>* _internal_mutable_victims();

  public:
  // uint64 buffId = 1;
  void clear_buffid() ;
  ::uint64_t buffid() const;
  void set_buffid(::uint64_t value);

  private:
  ::uint64_t _internal_buffid() const;
  void _internal_set_buffid(::uint64_t value);

  public:
  // float remainTime = 2;
  void clear_remaintime() ;
  float remaintime() const;
  void set_remaintime(float value);

  private:
  float _internal_remaintime() const;
  void _internal_set_remaintime(float value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.BuffData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BuffData& from_msg);
    ::google::protobuf::RepeatedField<::uint64_t> victims_;
    ::google::protobuf::internal::CachedSize _victims_cached_byte_size_;
    ::uint64_t buffid_;
    float remaintime_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class ObjectInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.ObjectInfo) */ {
 public:
  inline ObjectInfo() : ObjectInfo(nullptr) {}
  ~ObjectInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ObjectInfo* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ObjectInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ObjectInfo(
      ::google::protobuf::internal::ConstantInitialized);

  inline ObjectInfo(const ObjectInfo& from) : ObjectInfo(nullptr, from) {}
  inline ObjectInfo(ObjectInfo&& from) noexcept
      : ObjectInfo(nullptr, std::move(from)) {}
  inline ObjectInfo& operator=(const ObjectInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectInfo& operator=(ObjectInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObjectInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObjectInfo* internal_default_instance() {
    return reinterpret_cast<const ObjectInfo*>(
        &_ObjectInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ObjectInfo& a, ObjectInfo& b) { a.Swap(&b); }
  inline void Swap(ObjectInfo* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectInfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObjectInfo* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ObjectInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ObjectInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ObjectInfo& from) { ObjectInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ObjectInfo* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.ObjectInfo"; }

 protected:
  explicit ObjectInfo(::google::protobuf::Arena* arena);
  ObjectInfo(::google::protobuf::Arena* arena, const ObjectInfo& from);
  ObjectInfo(::google::protobuf::Arena* arena, ObjectInfo&& from) noexcept
      : ObjectInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 2,
    kStatFieldNumber = 3,
    kPosFieldNumber = 4,
    kObjectIdFieldNumber = 1,
    kRotYFieldNumber = 5,
    kObjectTypeFieldNumber = 6,
    kObjectStateFieldNumber = 10,
    kMoveDirFieldNumber = 11,
  };
  // string name = 2;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // .Protocol.CombatStat stat = 3;
  bool has_stat() const;
  void clear_stat() ;
  const ::Protocol::CombatStat& stat() const;
  PROTOBUF_NODISCARD ::Protocol::CombatStat* release_stat();
  ::Protocol::CombatStat* mutable_stat();
  void set_allocated_stat(::Protocol::CombatStat* value);
  void unsafe_arena_set_allocated_stat(::Protocol::CombatStat* value);
  ::Protocol::CombatStat* unsafe_arena_release_stat();

  private:
  const ::Protocol::CombatStat& _internal_stat() const;
  ::Protocol::CombatStat* _internal_mutable_stat();

  public:
  // .Protocol.Vec3 pos = 4;
  bool has_pos() const;
  void clear_pos() ;
  const ::Protocol::Vec3& pos() const;
  PROTOBUF_NODISCARD ::Protocol::Vec3* release_pos();
  ::Protocol::Vec3* mutable_pos();
  void set_allocated_pos(::Protocol::Vec3* value);
  void unsafe_arena_set_allocated_pos(::Protocol::Vec3* value);
  ::Protocol::Vec3* unsafe_arena_release_pos();

  private:
  const ::Protocol::Vec3& _internal_pos() const;
  ::Protocol::Vec3* _internal_mutable_pos();

  public:
  // uint64 objectId = 1;
  void clear_objectid() ;
  ::uint64_t objectid() const;
  void set_objectid(::uint64_t value);

  private:
  ::uint64_t _internal_objectid() const;
  void _internal_set_objectid(::uint64_t value);

  public:
  // float rot_y = 5;
  void clear_rot_y() ;
  float rot_y() const;
  void set_rot_y(float value);

  private:
  float _internal_rot_y() const;
  void _internal_set_rot_y(float value);

  public:
  // .Protocol.OBJECT_TYPE objectType = 6;
  void clear_objecttype() ;
  ::Protocol::OBJECT_TYPE objecttype() const;
  void set_objecttype(::Protocol::OBJECT_TYPE value);

  private:
  ::Protocol::OBJECT_TYPE _internal_objecttype() const;
  void _internal_set_objecttype(::Protocol::OBJECT_TYPE value);

  public:
  // .Protocol.OBJECT_STATE_TYPE object_state = 10;
  void clear_object_state() ;
  ::Protocol::OBJECT_STATE_TYPE object_state() const;
  void set_object_state(::Protocol::OBJECT_STATE_TYPE value);

  private:
  ::Protocol::OBJECT_STATE_TYPE _internal_object_state() const;
  void _internal_set_object_state(::Protocol::OBJECT_STATE_TYPE value);

  public:
  // .Protocol.MOVE_INPUT_DIR_TYPE move_dir = 11;
  void clear_move_dir() ;
  ::Protocol::MOVE_INPUT_DIR_TYPE move_dir() const;
  void set_move_dir(::Protocol::MOVE_INPUT_DIR_TYPE value);

  private:
  ::Protocol::MOVE_INPUT_DIR_TYPE _internal_move_dir() const;
  void _internal_set_move_dir(::Protocol::MOVE_INPUT_DIR_TYPE value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.ObjectInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 8, 2,
      40, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ObjectInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::Protocol::CombatStat* stat_;
    ::Protocol::Vec3* pos_;
    ::uint64_t objectid_;
    float rot_y_;
    int objecttype_;
    int object_state_;
    int move_dir_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Vec3

// float x = 1;
inline void Vec3::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline float Vec3::x() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec3.x)
  return _internal_x();
}
inline void Vec3::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec3.x)
}
inline float Vec3::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void Vec3::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 2;
inline void Vec3::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline float Vec3::y() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec3.y)
  return _internal_y();
}
inline void Vec3::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec3.y)
}
inline float Vec3::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void Vec3::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// float z = 3;
inline void Vec3::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
}
inline float Vec3::z() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec3.z)
  return _internal_z();
}
inline void Vec3::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec3.z)
}
inline float Vec3::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void Vec3::_internal_set_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// BuffData

// uint64 buffId = 1;
inline void BuffData::clear_buffid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.buffid_ = ::uint64_t{0u};
}
inline ::uint64_t BuffData::buffid() const {
  // @@protoc_insertion_point(field_get:Protocol.BuffData.buffId)
  return _internal_buffid();
}
inline void BuffData::set_buffid(::uint64_t value) {
  _internal_set_buffid(value);
  // @@protoc_insertion_point(field_set:Protocol.BuffData.buffId)
}
inline ::uint64_t BuffData::_internal_buffid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.buffid_;
}
inline void BuffData::_internal_set_buffid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.buffid_ = value;
}

// float remainTime = 2;
inline void BuffData::clear_remaintime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.remaintime_ = 0;
}
inline float BuffData::remaintime() const {
  // @@protoc_insertion_point(field_get:Protocol.BuffData.remainTime)
  return _internal_remaintime();
}
inline void BuffData::set_remaintime(float value) {
  _internal_set_remaintime(value);
  // @@protoc_insertion_point(field_set:Protocol.BuffData.remainTime)
}
inline float BuffData::_internal_remaintime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.remaintime_;
}
inline void BuffData::_internal_set_remaintime(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.remaintime_ = value;
}

// repeated uint64 victims = 3;
inline int BuffData::_internal_victims_size() const {
  return _internal_victims().size();
}
inline int BuffData::victims_size() const {
  return _internal_victims_size();
}
inline void BuffData::clear_victims() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.victims_.Clear();
}
inline ::uint64_t BuffData::victims(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.BuffData.victims)
  return _internal_victims().Get(index);
}
inline void BuffData::set_victims(int index, ::uint64_t value) {
  _internal_mutable_victims()->Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.BuffData.victims)
}
inline void BuffData::add_victims(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_victims()->Add(value);
  // @@protoc_insertion_point(field_add:Protocol.BuffData.victims)
}
inline const ::google::protobuf::RepeatedField<::uint64_t>& BuffData::victims() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Protocol.BuffData.victims)
  return _internal_victims();
}
inline ::google::protobuf::RepeatedField<::uint64_t>* BuffData::mutable_victims()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Protocol.BuffData.victims)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_victims();
}
inline const ::google::protobuf::RepeatedField<::uint64_t>&
BuffData::_internal_victims() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.victims_;
}
inline ::google::protobuf::RepeatedField<::uint64_t>* BuffData::_internal_mutable_victims() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.victims_;
}

// -------------------------------------------------------------------

// CombatStat

// float max_hp = 1;
inline void CombatStat::clear_max_hp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_hp_ = 0;
}
inline float CombatStat::max_hp() const {
  // @@protoc_insertion_point(field_get:Protocol.CombatStat.max_hp)
  return _internal_max_hp();
}
inline void CombatStat::set_max_hp(float value) {
  _internal_set_max_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.CombatStat.max_hp)
}
inline float CombatStat::_internal_max_hp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_hp_;
}
inline void CombatStat::_internal_set_max_hp(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_hp_ = value;
}

// float current_hp = 2;
inline void CombatStat::clear_current_hp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_hp_ = 0;
}
inline float CombatStat::current_hp() const {
  // @@protoc_insertion_point(field_get:Protocol.CombatStat.current_hp)
  return _internal_current_hp();
}
inline void CombatStat::set_current_hp(float value) {
  _internal_set_current_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.CombatStat.current_hp)
}
inline float CombatStat::_internal_current_hp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.current_hp_;
}
inline void CombatStat::_internal_set_current_hp(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_hp_ = value;
}

// float max_mp = 3;
inline void CombatStat::clear_max_mp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_mp_ = 0;
}
inline float CombatStat::max_mp() const {
  // @@protoc_insertion_point(field_get:Protocol.CombatStat.max_mp)
  return _internal_max_mp();
}
inline void CombatStat::set_max_mp(float value) {
  _internal_set_max_mp(value);
  // @@protoc_insertion_point(field_set:Protocol.CombatStat.max_mp)
}
inline float CombatStat::_internal_max_mp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_mp_;
}
inline void CombatStat::_internal_set_max_mp(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_mp_ = value;
}

// float current_mp = 4;
inline void CombatStat::clear_current_mp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_mp_ = 0;
}
inline float CombatStat::current_mp() const {
  // @@protoc_insertion_point(field_get:Protocol.CombatStat.current_mp)
  return _internal_current_mp();
}
inline void CombatStat::set_current_mp(float value) {
  _internal_set_current_mp(value);
  // @@protoc_insertion_point(field_set:Protocol.CombatStat.current_mp)
}
inline float CombatStat::_internal_current_mp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.current_mp_;
}
inline void CombatStat::_internal_set_current_mp(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_mp_ = value;
}

// float attack = 5;
inline void CombatStat::clear_attack() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attack_ = 0;
}
inline float CombatStat::attack() const {
  // @@protoc_insertion_point(field_get:Protocol.CombatStat.attack)
  return _internal_attack();
}
inline void CombatStat::set_attack(float value) {
  _internal_set_attack(value);
  // @@protoc_insertion_point(field_set:Protocol.CombatStat.attack)
}
inline float CombatStat::_internal_attack() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.attack_;
}
inline void CombatStat::_internal_set_attack(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attack_ = value;
}

// float defense = 6;
inline void CombatStat::clear_defense() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.defense_ = 0;
}
inline float CombatStat::defense() const {
  // @@protoc_insertion_point(field_get:Protocol.CombatStat.defense)
  return _internal_defense();
}
inline void CombatStat::set_defense(float value) {
  _internal_set_defense(value);
  // @@protoc_insertion_point(field_set:Protocol.CombatStat.defense)
}
inline float CombatStat::_internal_defense() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.defense_;
}
inline void CombatStat::_internal_set_defense(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.defense_ = value;
}

// float speed = 7;
inline void CombatStat::clear_speed() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speed_ = 0;
}
inline float CombatStat::speed() const {
  // @@protoc_insertion_point(field_get:Protocol.CombatStat.speed)
  return _internal_speed();
}
inline void CombatStat::set_speed(float value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:Protocol.CombatStat.speed)
}
inline float CombatStat::_internal_speed() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.speed_;
}
inline void CombatStat::_internal_set_speed(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speed_ = value;
}

// -------------------------------------------------------------------

// ObjectInfo

// uint64 objectId = 1;
inline void ObjectInfo::clear_objectid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objectid_ = ::uint64_t{0u};
}
inline ::uint64_t ObjectInfo::objectid() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.objectId)
  return _internal_objectid();
}
inline void ObjectInfo::set_objectid(::uint64_t value) {
  _internal_set_objectid(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.objectId)
}
inline ::uint64_t ObjectInfo::_internal_objectid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.objectid_;
}
inline void ObjectInfo::_internal_set_objectid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objectid_ = value;
}

// string name = 2;
inline void ObjectInfo::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& ObjectInfo::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ObjectInfo::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.name)
}
inline std::string* ObjectInfo::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Protocol.ObjectInfo.name)
  return _s;
}
inline const std::string& ObjectInfo::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void ObjectInfo::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline std::string* ObjectInfo::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* ObjectInfo::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.ObjectInfo.name)
  return _impl_.name_.Release();
}
inline void ObjectInfo::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.ObjectInfo.name)
}

// .Protocol.CombatStat stat = 3;
inline bool ObjectInfo::has_stat() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.stat_ != nullptr);
  return value;
}
inline void ObjectInfo::clear_stat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.stat_ != nullptr) _impl_.stat_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Protocol::CombatStat& ObjectInfo::_internal_stat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Protocol::CombatStat* p = _impl_.stat_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::CombatStat&>(::Protocol::_CombatStat_default_instance_);
}
inline const ::Protocol::CombatStat& ObjectInfo::stat() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.stat)
  return _internal_stat();
}
inline void ObjectInfo::unsafe_arena_set_allocated_stat(::Protocol::CombatStat* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.stat_);
  }
  _impl_.stat_ = reinterpret_cast<::Protocol::CombatStat*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.ObjectInfo.stat)
}
inline ::Protocol::CombatStat* ObjectInfo::release_stat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::CombatStat* released = _impl_.stat_;
  _impl_.stat_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Protocol::CombatStat* ObjectInfo::unsafe_arena_release_stat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.ObjectInfo.stat)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::CombatStat* temp = _impl_.stat_;
  _impl_.stat_ = nullptr;
  return temp;
}
inline ::Protocol::CombatStat* ObjectInfo::_internal_mutable_stat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.stat_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Protocol::CombatStat>(GetArena());
    _impl_.stat_ = reinterpret_cast<::Protocol::CombatStat*>(p);
  }
  return _impl_.stat_;
}
inline ::Protocol::CombatStat* ObjectInfo::mutable_stat() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Protocol::CombatStat* _msg = _internal_mutable_stat();
  // @@protoc_insertion_point(field_mutable:Protocol.ObjectInfo.stat)
  return _msg;
}
inline void ObjectInfo::set_allocated_stat(::Protocol::CombatStat* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.stat_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.stat_ = reinterpret_cast<::Protocol::CombatStat*>(value);
  // @@protoc_insertion_point(field_set_allocated:Protocol.ObjectInfo.stat)
}

// .Protocol.Vec3 pos = 4;
inline bool ObjectInfo::has_pos() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.pos_ != nullptr);
  return value;
}
inline void ObjectInfo::clear_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pos_ != nullptr) _impl_.pos_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::Protocol::Vec3& ObjectInfo::_internal_pos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Protocol::Vec3* p = _impl_.pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vec3&>(::Protocol::_Vec3_default_instance_);
}
inline const ::Protocol::Vec3& ObjectInfo::pos() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.pos)
  return _internal_pos();
}
inline void ObjectInfo::unsafe_arena_set_allocated_pos(::Protocol::Vec3* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pos_);
  }
  _impl_.pos_ = reinterpret_cast<::Protocol::Vec3*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.ObjectInfo.pos)
}
inline ::Protocol::Vec3* ObjectInfo::release_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Protocol::Vec3* released = _impl_.pos_;
  _impl_.pos_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Protocol::Vec3* ObjectInfo::unsafe_arena_release_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.ObjectInfo.pos)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Protocol::Vec3* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
  return temp;
}
inline ::Protocol::Vec3* ObjectInfo::_internal_mutable_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pos_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Protocol::Vec3>(GetArena());
    _impl_.pos_ = reinterpret_cast<::Protocol::Vec3*>(p);
  }
  return _impl_.pos_;
}
inline ::Protocol::Vec3* ObjectInfo::mutable_pos() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::Protocol::Vec3* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:Protocol.ObjectInfo.pos)
  return _msg;
}
inline void ObjectInfo::set_allocated_pos(::Protocol::Vec3* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.pos_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.pos_ = reinterpret_cast<::Protocol::Vec3*>(value);
  // @@protoc_insertion_point(field_set_allocated:Protocol.ObjectInfo.pos)
}

// float rot_y = 5;
inline void ObjectInfo::clear_rot_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rot_y_ = 0;
}
inline float ObjectInfo::rot_y() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.rot_y)
  return _internal_rot_y();
}
inline void ObjectInfo::set_rot_y(float value) {
  _internal_set_rot_y(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.rot_y)
}
inline float ObjectInfo::_internal_rot_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rot_y_;
}
inline void ObjectInfo::_internal_set_rot_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rot_y_ = value;
}

// .Protocol.OBJECT_TYPE objectType = 6;
inline void ObjectInfo::clear_objecttype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objecttype_ = 0;
}
inline ::Protocol::OBJECT_TYPE ObjectInfo::objecttype() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.objectType)
  return _internal_objecttype();
}
inline void ObjectInfo::set_objecttype(::Protocol::OBJECT_TYPE value) {
  _internal_set_objecttype(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.objectType)
}
inline ::Protocol::OBJECT_TYPE ObjectInfo::_internal_objecttype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::OBJECT_TYPE>(_impl_.objecttype_);
}
inline void ObjectInfo::_internal_set_objecttype(::Protocol::OBJECT_TYPE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objecttype_ = value;
}

// .Protocol.OBJECT_STATE_TYPE object_state = 10;
inline void ObjectInfo::clear_object_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_state_ = 0;
}
inline ::Protocol::OBJECT_STATE_TYPE ObjectInfo::object_state() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.object_state)
  return _internal_object_state();
}
inline void ObjectInfo::set_object_state(::Protocol::OBJECT_STATE_TYPE value) {
  _internal_set_object_state(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.object_state)
}
inline ::Protocol::OBJECT_STATE_TYPE ObjectInfo::_internal_object_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::OBJECT_STATE_TYPE>(_impl_.object_state_);
}
inline void ObjectInfo::_internal_set_object_state(::Protocol::OBJECT_STATE_TYPE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.object_state_ = value;
}

// .Protocol.MOVE_INPUT_DIR_TYPE move_dir = 11;
inline void ObjectInfo::clear_move_dir() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.move_dir_ = 0;
}
inline ::Protocol::MOVE_INPUT_DIR_TYPE ObjectInfo::move_dir() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.move_dir)
  return _internal_move_dir();
}
inline void ObjectInfo::set_move_dir(::Protocol::MOVE_INPUT_DIR_TYPE value) {
  _internal_set_move_dir(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.move_dir)
}
inline ::Protocol::MOVE_INPUT_DIR_TYPE ObjectInfo::_internal_move_dir() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::MOVE_INPUT_DIR_TYPE>(_impl_.move_dir_);
}
inline void ObjectInfo::_internal_set_move_dir(::Protocol::MOVE_INPUT_DIR_TYPE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.move_dir_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Struct_2eproto_2epb_2eh
