// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Enum.proto
// Protobuf C++ Version: 5.29.5

#ifndef Enum_2eproto_2epb_2eh
#define Enum_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Enum_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {
enum ComponentID : int {
  COMPONENT_TPYE_ENGINE_START = 0,
  COMPONENT_TYPE_TRANSFORM = 1,
  COMPONENT_TYPE_TEXTURE = 2,
  COMPONENT_TYPE_COLLIDER = 3,
  COMPONENT_TYPE_RECT = 4,
  COMPONENT_TYPE_SHADER = 5,
  COMPONENT_TYPE_TERRAIN = 6,
  COMPONENT_TYPE_MODEL = 7,
  COMPONENT_TYPE_AI = 100,
  COMPONENT_TYPE_CONTROLLER = 101,
  COMPONENT_TYPE_TEXTURE_START = 200,
  COMPONENT_TYPE_TEXTURE_DEFAULT = 201,
  COMPONENT_TYPE_TEXTURE_TERRAIN = 202,
  COMPONENT_TYPE_TEXTURE_PLAYER = 203,
  COMPONENT_TYPE_TEXTURE_MONSTER = 204,
  COMPONENT_TYPE_TEXTURE_MAIN_TITLE = 205,
  COMPONENT_TYPE_TEXTURE_LOADING = 206,
  COMPONENT_TYPE_TEXTURE_SKILL_ICON = 207,
  COMPONENT_TYPE_TEXTURE_PLAYER_STATUS = 208,
  COMPONENT_TYPE_MESH = 299,
  COMPONENT_TYPE_MODEL_START = 300,
  COMPONENT_TYPE_MODEL_PLAYER = 301,
  COMPONENT_TYPE_MODEL_MONSTER = 302,
  COMPONENT_TYPE_MODEL_SASKE = 303,
  COMPONENT_TYPE_SHADER_START = 400,
  COMPONENT_TYPE_SHADER_VTXTEX = 401,
  COMPONENT_TYPE_SHADER_VTXNORTEX = 402,
  COMPONENT_TYPE_SHADER_VTXMESH = 403,
  COMPONENT_TYPE_SHADER_UI = 404,
  COMPONENT_TYPE_SHADER_STATIC_MESH = 405,
  COMPONENT_TYPE_CLIENT_START = 1000,
  COMPONENT_TYPE_REPLICATOR = 1001,
  COMPONENT_TYPE_COMBAT_STAT = 1002,
  COMPONENT_TYPE_PLAYER_CONTROLLER = 1003,
  COMPONENT_TYPE_AI_CONTROLLER = 1004,
  COMPONENT_TYPE_MOVEMENT = 1005,
  COMPONENT_TYPE_INPUT = 1006,
  COMPONENT_TYPE_PLAYER_STATE = 1007,
  COMPONENT_TYPE_SKILL = 1008,
  ComponentID_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ComponentID_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ComponentID_IsValid(int value);
extern const uint32_t ComponentID_internal_data_[];
constexpr ComponentID ComponentID_MIN = static_cast<ComponentID>(0);
constexpr ComponentID ComponentID_MAX = static_cast<ComponentID>(1008);
constexpr int ComponentID_ARRAYSIZE = 1008 + 1;
const ::google::protobuf::EnumDescriptor*
ComponentID_descriptor();
template <typename T>
const std::string& ComponentID_Name(T value) {
  static_assert(std::is_same<T, ComponentID>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ComponentID_Name().");
  return ::google::protobuf::internal::NameOfEnum(ComponentID_descriptor(), value);
}
inline bool ComponentID_Parse(absl::string_view name, ComponentID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ComponentID>(
      ComponentID_descriptor(), name, value);
}
enum OBJECT_TYPE : int {
  OBJECT_TYPE_NONE = 0,
  OBJECT_TYPE_PLAYER = 1,
  OBJECT_TYPE_REMOTE_PLAYER = 2,
  OBJECT_TYPE_MONSTER = 4,
  OBJECT_TYPE_TERRAIN = 3,
  OBJECT_TYPE_CAMERA_FREE = 5,
  OBJECT_TYPE_CAMERA_TARGET = 6,
  OBJECT_TYPE_PLAYER_START = 7,
  OBJECT_TYPE_BACKGROUND = 10,
  OBJECT_TYPE_STATIC_MESH = 11,
  OBJECT_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  OBJECT_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool OBJECT_TYPE_IsValid(int value);
extern const uint32_t OBJECT_TYPE_internal_data_[];
constexpr OBJECT_TYPE OBJECT_TYPE_MIN = static_cast<OBJECT_TYPE>(0);
constexpr OBJECT_TYPE OBJECT_TYPE_MAX = static_cast<OBJECT_TYPE>(11);
constexpr int OBJECT_TYPE_ARRAYSIZE = 11 + 1;
const ::google::protobuf::EnumDescriptor*
OBJECT_TYPE_descriptor();
template <typename T>
const std::string& OBJECT_TYPE_Name(T value) {
  static_assert(std::is_same<T, OBJECT_TYPE>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to OBJECT_TYPE_Name().");
  return OBJECT_TYPE_Name(static_cast<OBJECT_TYPE>(value));
}
template <>
inline const std::string& OBJECT_TYPE_Name(OBJECT_TYPE value) {
  return ::google::protobuf::internal::NameOfDenseEnum<OBJECT_TYPE_descriptor,
                                                 0, 11>(
      static_cast<int>(value));
}
inline bool OBJECT_TYPE_Parse(absl::string_view name, OBJECT_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OBJECT_TYPE>(
      OBJECT_TYPE_descriptor(), name, value);
}
enum OBJECT_STATE_TYPE : int {
  OBJECT_STATE_TYPE_IDLE = 0,
  OBJECT_STATE_TYPE_MOVE = 1,
  OBJECT_STATE_TYPE_SKILL = 2,
  OBJECT_STATE_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  OBJECT_STATE_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool OBJECT_STATE_TYPE_IsValid(int value);
extern const uint32_t OBJECT_STATE_TYPE_internal_data_[];
constexpr OBJECT_STATE_TYPE OBJECT_STATE_TYPE_MIN = static_cast<OBJECT_STATE_TYPE>(0);
constexpr OBJECT_STATE_TYPE OBJECT_STATE_TYPE_MAX = static_cast<OBJECT_STATE_TYPE>(2);
constexpr int OBJECT_STATE_TYPE_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
OBJECT_STATE_TYPE_descriptor();
template <typename T>
const std::string& OBJECT_STATE_TYPE_Name(T value) {
  static_assert(std::is_same<T, OBJECT_STATE_TYPE>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to OBJECT_STATE_TYPE_Name().");
  return OBJECT_STATE_TYPE_Name(static_cast<OBJECT_STATE_TYPE>(value));
}
template <>
inline const std::string& OBJECT_STATE_TYPE_Name(OBJECT_STATE_TYPE value) {
  return ::google::protobuf::internal::NameOfDenseEnum<OBJECT_STATE_TYPE_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool OBJECT_STATE_TYPE_Parse(absl::string_view name, OBJECT_STATE_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OBJECT_STATE_TYPE>(
      OBJECT_STATE_TYPE_descriptor(), name, value);
}
enum DIR_TYPE : int {
  DIR_TYPE_UP = 0,
  DIR_TYPE_DOWN = 1,
  DIR_TYPE_LEFT = 2,
  DIR_TYPE_RIGHT = 3,
  DIR_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  DIR_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool DIR_TYPE_IsValid(int value);
extern const uint32_t DIR_TYPE_internal_data_[];
constexpr DIR_TYPE DIR_TYPE_MIN = static_cast<DIR_TYPE>(0);
constexpr DIR_TYPE DIR_TYPE_MAX = static_cast<DIR_TYPE>(3);
constexpr int DIR_TYPE_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
DIR_TYPE_descriptor();
template <typename T>
const std::string& DIR_TYPE_Name(T value) {
  static_assert(std::is_same<T, DIR_TYPE>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DIR_TYPE_Name().");
  return DIR_TYPE_Name(static_cast<DIR_TYPE>(value));
}
template <>
inline const std::string& DIR_TYPE_Name(DIR_TYPE value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DIR_TYPE_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool DIR_TYPE_Parse(absl::string_view name, DIR_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DIR_TYPE>(
      DIR_TYPE_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Protocol::ComponentID> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::ComponentID>() {
  return ::Protocol::ComponentID_descriptor();
}
template <>
struct is_proto_enum<::Protocol::OBJECT_TYPE> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::OBJECT_TYPE>() {
  return ::Protocol::OBJECT_TYPE_descriptor();
}
template <>
struct is_proto_enum<::Protocol::OBJECT_STATE_TYPE> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::OBJECT_STATE_TYPE>() {
  return ::Protocol::OBJECT_STATE_TYPE_descriptor();
}
template <>
struct is_proto_enum<::Protocol::DIR_TYPE> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::DIR_TYPE>() {
  return ::Protocol::DIR_TYPE_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Enum_2eproto_2epb_2eh
