syntax = "proto3";
package Protocol;

enum ComponentID
{
    COMPONENT_TPYE_ENGINE_START = 0;

    // Engine ComponentID
    COMPONENT_TYPE_TRANSFORM            = 1;
    COMPONENT_TYPE_TEXTURE              = 2;
    COMPONENT_TYPE_COLLIDER             = 3;
    COMPONENT_TYPE_RECT                 = 4;
    COMPONENT_TYPE_SHADER               = 5;

    COMPONENT_TYPE_TEXTURE_DEFAULT      = 99;
    COMPONENT_TYPE_AI                   = 100;
    COMPONENT_TYPE_CONTROLLER           = 101;
    
    // Client ComponentID
    COMPONENT_TYPE_CLIENT_START         = 1000;
    COMPONENT_TYPE_REPLICATOR           = 1001;
    COMPONENT_TYPE_COMBAT_STAT          = 1002;
    COMPONENT_TYPE_PLAYER_CONTROLLER    = 1003;
    COMPONENT_TYPE_AI_CONTROLLER        = 1004;
    COMPONENT_TYPE_MOVEMENT             = 1005;
    COMPONENT_TYPE_INPUT                = 1006;
}

enum OBJECT_TYPE
{
	OBJECT_TYPE_NONE = 0;
	OBJECT_TYPE_PLAYER = 1;
	OBJECT_TYPE_MONSTER = 2;

    OBJECT_TYPE_BACKGROUND = 10;
}

enum OBJECT_STATE_TYPE
{
	OBJECT_STATE_TYPE_IDLE = 0;
	OBJECT_STATE_TYPE_MOVE = 1;
	OBJECT_STATE_TYPE_SKILL = 2;
}

enum DIR_TYPE
{
	DIR_TYPE_UP = 0;
	DIR_TYPE_DOWN = 1;
	DIR_TYPE_LEFT = 2;
	DIR_TYPE_RIGHT = 3;
}
