syntax = "proto3";
package Protocol;

enum ComponentID
{
    // Engine ComponentID
    COMPONENT_TPYE_ENGINE_START             = 0;
    COMPONENT_TYPE_TRANSFORM                = 1;
    COMPONENT_TYPE_TEXTURE                  = 2;
    COMPONENT_TYPE_COLLIDER                 = 3;
    COMPONENT_TYPE_RECT                     = 4;
    COMPONENT_TYPE_SHADER                   = 5;
    COMPONENT_TYPE_TERRAIN                  = 6;
    COMPONENT_TYPE_MODEL                    = 7;
    COMPONENT_TYPE_PROJECTILE               = 8;
    COMPONENT_TYPE_VIBUFFER_PARTICLE_POINT  = 9;
    COMPONENT_TYPE_EFFECT                   = 10;
    COMPONENT_TYPE_VIBUFFER_TRAIL           = 11;
    
    COMPONENT_TYPE_COLLIDER_AABB         = 21;
    COMPONENT_TYPE_COLLIDER_OBB          = 22;
    COMPONENT_TYPE_COLLIDER_SPHERE       = 23;
    COMPONENT_TYPE_COLLIDER_CAPSULE      = 24;
  
    COMPONENT_TYPE_BEHAVIOR              = 100;
    COMPONENT_TYPE_CONTROLLER            = 101;

   

    // Texture : 200+
    COMPONENT_TYPE_TEXTURE_START          = 200;
    COMPONENT_TYPE_TEXTURE_DEFAULT        = 201;
    COMPONENT_TYPE_TEXTURE_TERRAIN        = 202;
    COMPONENT_TYPE_TEXTURE_PLAYER         = 203;
    COMPONENT_TYPE_TEXTURE_MONSTER        = 204;
    COMPONENT_TYPE_TEXTURE_MAIN_TITLE     = 205;
    COMPONENT_TYPE_TEXTURE_LOADING        = 206;
    COMPONENT_TYPE_TEXTURE_SKILL_GAUGE    = 207;
    COMPONENT_TYPE_TEXTURE_SKILL_ICON     = 208;
    COMPONENT_TYPE_TEXTURE_PLAYER_STATUS  = 209;
    COMPONENT_TYPE_TEXTURE_EQUIPMENT      = 210;
    COMPONENT_TYPE_TEXTURE_SKILL_SUB      = 211;
    COMPONENT_TYPE_TEXTURE_WEAPON_TYPE    = 212;

    COMPONENT_TYPE_TEXTURE_ANNOUNCE_HIT   = 213;
    COMPONENT_TYPE_TEXTURE_ANNOUNCE_DIGIT = 214;
    COMPONENT_TYPE_TEXTURE_TARGET         = 215;
    COMPONENT_TYPE_TEXTURE_PARTICLE_SNOW  = 216;   
    COMPONENT_TYPE_TEXTURE_PARTICLE_EXPLOSION = 217;

    COMPONENT_TYPE_TEXTURE_PARTICLE_HIT = 218;
    COMPONENT_TYPE_TEXTURE_TRAIL        = 219;

    COMPONENT_TYPE_TEXTURE_SWORD_TRAIL = 220;
        
    COMPONENT_TYPE_MONSTER_HP           = 221;
    COMPONENT_TYPE_BOSS_HP              = 222;

    COMPONENT_TYPE_TEXTURE_SKY_SPHERE   = 223;


    // Mesh
    COMPONENT_TYPE_MESH                 = 299;

    // Model : 300+
    COMPONENT_TYPE_MODEL_START          = 300;
    COMPONENT_TYPE_MODEL_PLAYER         = 301;
    COMPONENT_TYPE_MODEL_MONSTER        = 302;
    COMPONENT_TYPE_MODEL_SASKE          = 303;

    // Shader : 400+
    COMPONENT_TYPE_SHADER_START         = 400;
    COMPONENT_TYPE_SHADER_VTXTEX        = 401;
    COMPONENT_TYPE_SHADER_VTXNORTEX     = 402;
    COMPONENT_TYPE_SHADER_VTXMESH       = 403;
    COMPONENT_TYPE_SHADER_VTXANIMMESH   = 404;
    COMPONENT_TYPE_SHADER_UI            = 405;
    COMPONENT_TYPE_SHADER_STATIC_MESH   = 406;
    COMPONENT_TYPE_SHADER_GHOST_EFFECT  = 407;
    COMPONENT_TYPE_SHADER_SMEAR_EFFECT  = 408;
    COMPONENT_TYPE_SHADER_PARTICLE_POINT = 409;
    COMPONENT_TYPE_SHADER_EFFECT_MESH    = 410;
    COMPONENT_TYPE_SHADER_BILLBOARD      = 411;
    COMPONENT_TYPE_SHADER_CHAKRA         = 412;
    COMPONENT_TYPE_SHADER_SWORD_TRAIL    = 413;
    COMPONENT_TYPE_SHADER_SKYSPHERE      = 414;
    COMPONENT_TYPE_SHADER_EFFECT_SKELETAL_MESH = 415;

    // Client ComponentID
    COMPONENT_TYPE_CLIENT_START         = 1000;
    COMPONENT_TYPE_REPLICATOR           = 1001;
    COMPONENT_TYPE_COMBAT_STAT          = 1002;
    COMPONENT_TYPE_PLAYER_CONTROLLER    = 1003;
    COMPONENT_TYPE_AI_CONTROLLER        = 1004;
    COMPONENT_TYPE_MOVEMENT             = 1005;
    COMPONENT_TYPE_INPUT                = 1006;
    COMPONENT_TYPE_PLAYER_STATE         = 1007;
    COMPONENT_TYPE_SKILL                = 1008;
    COMPONENT_TYPE_ANIMATION_STATE      = 1009;
    COMPONENT_TYPE_EQUIPMENT            = 1010;
    COMPONENT_TYPE_TARGET               = 1011;
    COMPONENT_TYPE_GHOST_EFFECT         = 1012;
    COMPONENT_TYPE_SMEAR_EFFECT         = 1013;
    COMPONENT_TYPE_TRAIL                = 1014;
    COMPONENT_TYPE_CHAKRA_MOVE          = 1015;
    COMPONENT_TYPE_SWORD_TRAIL          = 1016;

}

enum OBJECT_TYPE
{
	OBJECT_TYPE_NONE                    = 0;
	OBJECT_TYPE_PLAYER                  = 1;
    OBJECT_TYPE_REMOTE_PLAYER           = 2;
    OBJECT_TYPE_PREVIEW_PLAYER          = 3;
	OBJECT_TYPE_MONSTER                 = 4;
    OBJECT_TYPE_CAMERA_FREE             = 5;
    OBJECT_TYPE_CAMERA_TARGET           = 6;
    OBJECT_TYPE_CAMERA_CINEMATIC        = 7;

    OBJECT_TYPE_PLAYER_START            = 10;
    OBJECT_TYPE_TERRAIN                 = 11;

    OBJECT_TYPE_BACKGROUND              = 12;
    OBJECT_TYPE_STATIC_MESH             = 13;

    OBJECT_TYPE_PART_OBJECT             = 14;
    OBJECT_TYPE_PART_WEAPON             = 15; // 무기는 뼈대가 없는 StaticMesdh

    OBJECT_TYPE_SKILL_OBJECT            = 16;
    OBJECT_TYPE_SKILL_PROJECTILE        = 17;

    

    // 실제 사용 스킬
    OBJECT_TYPE_SKILL_RASENGAN          = 18;
    OBJECT_TYPE_SKILL_RASENSHURIKEN     = 19;
    OBJECT_TYPE_SKILL_FIREBALL          = 20;
    OBJECT_TYPE_SKILL_CHIDORI           = 21;

    OBJECT_TYPE_SKILL_RASENSHURIKEN_HIT = 22;
    OBJECT_TYPE_SKILL_RASENGAN_HIT = 23;
    OBJECT_TYPE_SKILL_CHIDORI_HIT = 24;

    OBJECT_TYPE_SHINSUSENJU = 25;
    OBJECT_TYPE_KIRIN = 26;
    OBJECT_TYPE_SHINSUSENJU_ARM = 27;
    OBJECT_TYPE_KIRIN_HIT = 28;
    OBJECT_TYPE_SHINSUSENJU_IMPACT = 29;

    OBJECT_TYPE_SKILL_MONSTER_ATTACK    = 40;

    // 인스턴스 포인트
    OBJECT_TYPE_INSTANCED_PARTICLE_POINT = 60;
    OBJECT_TYPE_EFFECT_MESH              = 61;  
    OBJECT_TYPE_EFFECT_BILLBOARD         = 62;

    // 땜빵
    OBJECT_TYPE_ATTACHED_EFFECT          = 80;
    OBJECT_TYPE_STRETCHING_MESH_EFFECT   = 81;
    OBJECT_TYPE_COLLISION_PROXY          = 82;
    OBJECT_TYPE_SKY_SPHERE               = 83;

    OBJECT_TYPE_SHURIKEN                 = 84;
   
    // 메쉬 파티클
    OBJECT_TYPE_MESH_DEBRIS = 85;

    OBJECT_TYPE_BOSS_PAIN = 86;

    // UI : 100+
    OBJECT_TYPE_UI_TEXT                 = 100;
    OBJECT_TYPE_UI_LOADING_SPINNER      = 101;
    OBJECT_TYPE_UI_LOADING_PROGRESS_BAR = 102;
    OBJECT_TYPE_UI_MAIN_TITLE_TEXT      = 103;
    OBJECT_TYPE_UI_PLAYER_HP            = 104;
    OBJECT_TYPE_UI_SKILL_SLOT           = 105;
    OBJECT_TYPE_UI_PLAYER_STATUS        = 106;
    OBJECT_TYPE_UI_PLAYER_SKILL         = 107;
    OBJECT_TYPE_UI_PLAYER_HUD           = 108;
    OBJECT_TYPE_UI_TAB                  = 109;
    OBJECT_TYPE_UI_WEAPON_TYPE          = 110;

    OBJECT_TYPE_UI_ANNOUNCE_COMBO       = 111;
    OBJECT_TYPE_UI_TARGETING            = 112;

    OBJECT_TYPE_UI_MONSTER_HP           = 113;
    OBJECT_TYPE_UI_BOSS_HP              = 114;
                
    OBJECT_TYPE_UI_MULTIPLAYER_HP       = 115;
}

enum OBJECT_STATE_TYPE
{
    OBJECT_STATE_TYPE_IDLE = 0;
    OBJECT_STATE_TYPE_RUN = 1;
    OBJECT_STATE_TYPE_JUMP = 2;
    OBJECT_STATE_TYPE_DOUBLE_JUMP = 3;
    OBJECT_STATE_TYPE_SUPER_JUMP_CHARGE = 4;
    OBJECT_STATE_TYPE_SUPER_JUMP = 5;
    OBJECT_STATE_TYPE_HEIGHT_LAND = 6;
    OBJECT_STATE_TYPE_DASH = 7;

    OBJECT_STATE_TYPE_BIGSWORD_IDLE = 8;
    OBJECT_STATE_TYPE_WALL_IDLE = 9;
    OBJECT_STATE_TYPE_WALL_RUN = 10;
    OBJECT_STATE_TYPE_JUMP_FALL = 11;
    OBJECT_STATE_TYPE_JUMP_DASH = 12;
    OBJECT_STATE_TYPE_WIRE_DASH = 13;
    OBJECT_STATE_TYPE_AIR_APPROACH = 14;

    OBJECT_STATE_TYPE_ATTACK = 15;
    OBJECT_STATE_TYPE_JUMP_ATTACK = 16;

    OBJECT_STATE_TYPE_ATTACK_01 = 17;
    OBJECT_STATE_TYPE_ATTACK_02 = 18;
    OBJECT_STATE_TYPE_ATTACK_03 = 19;
    OBJECT_STATE_TYPE_ATTACK_04 = 20;
    OBJECT_STATE_TYPE_ATTACK_AIR_01 = 21;
    OBJECT_STATE_TYPE_ATTACK_AIR_02 = 22;
    OBJECT_STATE_TYPE_ATTACK_AIR_03 = 23;
    OBJECT_STATE_TYPE_ATTACK_AIR_04 = 24;
    OBJECT_STATE_TYPE_ATTACK_SWORD_01 = 25;
    OBJECT_STATE_TYPE_ATTACK_SWORD_02 = 26;
    OBJECT_STATE_TYPE_ATTACK_SWORD_03 = 27;
    OBJECT_STATE_TYPE_ATTACK_SWORD_04 = 28;
    OBJECT_STATE_TYPE_ATTACK_SWORD_AIR_01 = 29;
    OBJECT_STATE_TYPE_ATTACK_SWORD_AIR_02 = 30;

    OBJECT_STATE_TYPE_HIT = 31;

    OBJECT_STATE_TYPE_SKILL_RASENGAN = 32;
    OBJECT_STATE_TYPE_SKILL_RASENGAN_AIR = 33;
    OBJECT_STATE_TYPE_SKILL_RASENGAN_END = 34;
    OBJECT_STATE_TYPE_SKILL_RASENSHURIKEN = 35;
    OBJECT_STATE_TYPE_SKILL_RASENSHURIKEN_AIR = 36;
    OBJECT_STATE_TYPE_SKILL_CHIDORI = 37;
    OBJECT_STATE_TYPE_SKILL_CHIDORI_AIR = 38;
    OBJECT_STATE_TYPE_SKILL_CHIDORI_END = 39;
    OBJECT_STATE_TYPE_SKILL_FIREBALL = 40;
    OBJECT_STATE_TYPE_SKILL_FIREBALL_AIR = 41;

    OBJECT_STATE_TYPE_DEAD = 42;
}
enum MOVE_INPUT_DIR_TYPE
{
    MOVE_INPUT_DIR_TYPE_FORWARD = 0;
    MOVE_INPUT_DIR_TYPE_BACKWARD = 1;
    MOVE_INPUT_DIR_TYPE_LEFT = 2;
    MOVE_INPUT_DIR_TYPE_RIGHT = 3;
}

enum ANIM_PHASE_TYPE
{
    ANIM_PHASE_START = 0;
    ANIM_PHASE_LOOP  = 1;
    ANIM_PHASE_END   = 2;
}

enum ATTACK_PROFILE_TYPE
{
    ATTACK_PROFILE_TYPE_HAND_GROUND          = 0;
    ATTACK_PROFILE_TYPE_HAND_AERIAL          = 1;
    ATTACK_PROFILE_TYPE_BIGSWORD_GROUND      = 2;
    ATTACK_PROFILE_TYPE_BIGSWORD_AERIAL      = 3;
}
