syntax = "proto3";
package Protocol;

enum ComponentID
{
    // Engine ComponentID
    COMPONENT_TPYE_ENGINE_START = 0;
    COMPONENT_TYPE_TRANSFORM            = 1;
    COMPONENT_TYPE_TEXTURE              = 2;
    COMPONENT_TYPE_COLLIDER             = 3;
    COMPONENT_TYPE_RECT                 = 4;
    COMPONENT_TYPE_SHADER               = 5;
    COMPONENT_TYPE_TERRAIN              = 6;
    COMPONENT_TYPE_MODEL                = 7;

    COMPONENT_TYPE_AI                   = 100;
    COMPONENT_TYPE_CONTROLLER           = 101;

    // Texture : 200+
    COMPONENT_TYPE_TEXTURE_START        = 200;
    COMPONENT_TYPE_TEXTURE_DEFAULT      = 201;
    COMPONENT_TYPE_TEXTURE_TERRAIN      = 202;
    COMPONENT_TYPE_TEXTURE_PLAYER       = 203;
    COMPONENT_TYPE_TEXTURE_MONSTER      = 204;
    COMPONENT_TYPE_TEXTURE_MAIN_TITLE   = 205;
    COMPONENT_TYPE_TEXTURE_LOADING      = 206;
    COMPONENT_TYPE_TEXTURE_SKILL_ICON   = 207;
    COMPONENT_TYPE_TEXTURE_PLAYER_STATUS = 208;

    // Mesh
    COMPONENT_TYPE_MESH                 = 299;

    // Model : 300+
    COMPONENT_TYPE_MODEL_START          = 300;
    COMPONENT_TYPE_MODEL_PLAYER         = 301;
    COMPONENT_TYPE_MODEL_MONSTER        = 302;

    // Shader : 400+
    COMPONENT_TYPE_SHADER_START         = 400;
    COMPONENT_TYPE_SHADER_VTXTEX        = 401;
    COMPONENT_TYPE_SHADER_VTXNORTEX     = 402;
    COMPONENT_TYPE_SHADER_VTXMESH       = 403;


    // Client ComponentID
    COMPONENT_TYPE_CLIENT_START         = 1000;
    COMPONENT_TYPE_REPLICATOR           = 1001;
    COMPONENT_TYPE_COMBAT_STAT          = 1002;
    COMPONENT_TYPE_PLAYER_CONTROLLER    = 1003;
    COMPONENT_TYPE_AI_CONTROLLER        = 1004;
    COMPONENT_TYPE_MOVEMENT             = 1005;
    COMPONENT_TYPE_INPUT                = 1006;
    COMPONENT_TYPE_PLAYER_STATE         = 1007;
}

enum OBJECT_TYPE
{
	OBJECT_TYPE_NONE                    = 0;
	OBJECT_TYPE_PLAYER                  = 1;
    OBJECT_TYPE_REMOTE_PLAYER           = 2;
	OBJECT_TYPE_MONSTER                 = 4;
    OBJECT_TYPE_TERRAIN                 = 3;
    OBJECT_TYPE_CAMERA_FREE             = 5;
    OBJECT_TYPE_CAMERA_TARGET           = 6;
    OBJECT_TYPE_PLAYER_START            = 7;

    OBJECT_TYPE_BACKGROUND              = 10;
    OBJECT_TYPE_STATIC_MESH             = 11;
}

enum OBJECT_STATE_TYPE
{
	OBJECT_STATE_TYPE_IDLE              = 0;
	OBJECT_STATE_TYPE_MOVE              = 1;
	OBJECT_STATE_TYPE_SKILL             = 2;
}

enum DIR_TYPE
{
	DIR_TYPE_UP                         = 0;
	DIR_TYPE_DOWN                       = 1;
	DIR_TYPE_LEFT                       = 2;
	DIR_TYPE_RIGHT                      = 3;
}
