syntax = "proto3";
package Protocol;

import "Enum.proto";
import "Struct.proto";

message S_TEST
{
	uint64 id = 1;
	uint32 hp = 2;
	uint32 attack = 3;
	repeated BuffData buffs = 4;
}

message S_EnterGame
{
	bool success = 1;
	uint64 accountId = 2;
}

message S_MyPlayer
{
	ObjectInfo info = 1;
}

message S_AddObject
{
	repeated ObjectInfo objects = 1;
}

message S_RemoveObject
{
	repeated uint64 ids = 1;
}

message S_WaveCleared
{
    string wave_tag = 1;
}

message C_EnterGame
{
    Vec3  spawn_pos = 1;
    float rot_y = 2;
    ObjectInfo info = 3;
}

message C_Move
{
	ObjectInfo info = 1;
}

message S_Move
{
	ObjectInfo info = 1;
}

message S_UpdateStat
{
    uint64 player_id = 1;
    CombatStat stat = 2;
}

message LobbyPlayerInfo
{
    uint64      lobby_id = 1;
    uint32      slot = 2;
    ObjectInfo  info = 3;
    bool        is_host = 4;
}
message C_LobbyJoin
{
    ObjectInfo info = 1;
}

message S_LobbySnapshot
{
    repeated LobbyPlayerInfo players = 1;
    uint64 my_lobby_id = 2;
}

message C_LobbyChat
{
    string message = 1;
}

message S_LobbyChat
{
    uint64 lobby_id = 1;
    string name = 2;
    string message = 3;
}

message C_LobbyStartGame
{
}

message S_LobbyStartGame
{
}

