syntax = "proto3";
package Protocol;

import "Enum.proto";

message Vec3
{
    float x = 1;
    float y = 2;
    float z = 3;
}

message BuffData
{
	uint64 buffId = 1;
	float remainTime = 2;
	repeated uint64 victims = 3;
}

message CombatStat
{ 
    float max_hp = 1;
    float current_hp = 2;

    float max_mp = 3;
    float current_mp = 4;

    float attack = 5;
    float defense = 6;
    float speed = 7;
}

message ObjectInfo
{
	uint64              objectId = 1;
	string              name = 2;
    CombatStat          stat = 3;

    Vec3                pos = 4;
    float               rot_y = 5;

    OBJECT_TYPE         objectType = 6;

    OBJECT_STATE_TYPE   object_state = 10;
    MOVE_INPUT_DIR_TYPE move_dir = 11;
}
